name: icon_font_generator
version: 4.0.1
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/ScerIO/icon_font_generator

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dart_style: ^3.0.1
  logger: ^2.6.1
  meta: ^1.16.0
  path: ^1.9.1
  path_parsing: ^1.1.0
  pub_semver: ^2.2.0
  recase: ^4.1.0
  vector_math: ^2.2.0
  xml: ^6.6.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  
executables:
  generator: generator